name: Django CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - python-version: 3.7
            django-version: '2.2'
          - python-version: 3.7
            django-version: '3.0'
          - python-version: 3.7
            django-version: '3.1'
          - python-version: 3.7
            django-version: '3.2'

          - python-version: 3.8
            django-version: '2.2'
          - python-version: 3.8
            django-version: '3.0'
          - python-version: 3.8
            django-version: '3.1'
          - python-version: 3.8
            django-version: '3.2'
          - python-version: 3.8
            django-version: '4.0'
          - python-version: 3.8
            django-version: '4.1'
          - python-version: 3.8
            django-version: '4.2'

          - python-version: 3.9
            django-version: '2.2'
          - python-version: 3.9
            django-version: '3.0'
          - python-version: 3.9
            django-version: '3.1'
          - python-version: 3.9
            django-version: '3.2'
          - python-version: 3.9
            django-version: '4.0'
          - python-version: 3.9
            django-version: '4.1'
          - python-version: 3.9
            django-version: '4.2'

          - python-version: 3.10
            django-version: '2.2'
          - python-version: 3.10
            django-version: '3.0'
          - python-version: 3.10
            django-version: '3.1'
          - python-version: 3.10
            django-version: '3.2'
          - python-version: 3.10
            django-version: '4.1'
          - python-version: 3.10
            django-version: '4.2'
          - python-version: 3.10
            django-version: '5.0'
          - python-version: 3.10
            django-version: '5.1'

          - python-version: 3.11
            django-version: '4.1'
          - python-version: 3.11
            django-version: '4.2'
          - python-version: 3.11
            django-version: '5.0'
          - python-version: 3.11
            django-version: '5.1'

          - python-version: 3.12
            django-version: '4.1'
          - python-version: 3.12
            django-version: '4.2'
          - python-version: 3.12
            django-version: '5.0'
          - python-version: 3.12
            django-version: '5.1'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django==${{ matrix.django-version }} pytest pytest-django

      - name: Run tests
        run: |
          pytest tests --ds=test_project.settings
